# Generated by Django 4.0.4 on 2022-04-21 20:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 20, 50, 20, 873756, tzinfo=utc)),
        ),
    ]
