# Generated by Django 4.0.4 on 2022-04-21 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_show_alter_contato_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 22, 56, 32, 517146, tzinfo=utc)),
        ),
    ]
